### ISSUE TITLE
[FIXED] TypeError: only pages can be inserted with libqpdf >= 10.2.0 **AND**  pikepdf < 2.7.0

### ISSUE THREAD

**Issue by sillysimon** [pdfarranger/pdfarranger#427]
*Moderation Edit:*
in most cases the answer is `pip install --upgrade pikepdf`
Update: 1.7.1 includes a workaround. Upgrade what ever is more convenient for you.
/@dreua

---------

Hi there,
I have a problem with the arch software package version of the software. Every time I try to save a modified document it does not do so but instead throws the following error:
```python
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pdfarranger/pdfarranger.py", line 695, in choose_export_pdf_name
    self.save(mode, file_out)
  File "/usr/lib/python3.9/site-packages/pdfarranger/pdfarranger.py", line 157, in wrapper
    func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pdfarranger/pdfarranger.py", line 769, in save
    exporter.export(self.pdfqueue, to_export, file_out, mode, m)
  File "/usr/lib/python3.9/site-packages/pdfarranger/exporter.py", line 168, in export
    pdf_output.pages.append(new_page)
TypeError: only pages can be inserted
```
if I use the flatpak version it works fine. Although I would really prefer to use the native arch package

**Comment by jeromerobert** [comment]
Could apply the following changes to help finding the bug:
```patch
--- a/pdfarranger/exporter.py
+++ b/pdfarranger/exporter.py
@@ -97,6 +97,7 @@ def _scale(doc, page, factor):
         Resources={'/XObject': {'/p{}'.format(page_id): xobject}},
         Rotate=rotate,
     )
+    print("end of _scale", type(new_page), new_page)
     return new_page
 
 def check_content(parent, pdf_list):
@@ -150,6 +151,7 @@ def export(input_files, pages, file_out, mode, mdata):
         try:
             new_page = copy.copy(new_page)
         except TypeError:
+            traceback.print_exc()
             if _report_pikepdf_err:
                 _report_pikepdf_err = False
                 traceback.print_exc()
@@ -157,6 +159,7 @@ def export(input_files, pages, file_out, mode, mdata):
                       "1.7.0 or greater. Continuing but pdfarranger will not "
                       "work properly.".format(pikepdf.__version__),
                       file=sys.stderr)
+        print("new_page copy", type(new_page), new_page)
         if angle != 0:
             new_page.Rotate = angle + angle0
         # PDF files which do not have mediabox default to Portrait Letter / ANSI A
```

**Comment by Just-Another-Gnumer** [comment]
I have the exact same problem (same day) on a source build of (1.70) on Ubuntu 18.04. I thought it might have had something to with my distro being old but to find an Arch user having problems is a sign that it may be something else.

I used a pip3 trick to install the latest pikepdf and other libraries. Hope we can resolve this, the flatpak version and 1.31 does not have this problem.

**Comment by sillysimon** [comment]
>Could apply the following changes to help finding the bug: 
>```diff
> --- a/pdfarranger/exporter.py
> +++ b/pdfarranger/exporter.py
> @@ -97,6 +97,7 @@ def _scale(doc, page, factor):
>          Resources={'/XObject': {'/p{}'.format(page_id): xobject}},
>          Rotate=rotate,
>      )
> +    print("end of _scale", type(new_page), new_page)
>      return new_page
>  
>  def check_content(parent, pdf_list):
> @@ -150,6 +151,7 @@ def export(input_files, pages, file_out, mode, mdata):
>          try:
>              new_page = copy.copy(new_page)
>          except TypeError:
> +            traceback.print_exc()
>              if _report_pikepdf_err:
>                  _report_pikepdf_err = False
>                  traceback.print_exc()
> @@ -157,6 +159,7 @@ def export(input_files, pages, file_out, mode, mdata):
>                        "1.7.0 or greater. Continuing but pdfarranger will not "
>                        "work properly.".format(pikepdf.__version__),
>                        file=sys.stderr)
> +        print("new_page copy", type(new_page), new_page)
>          if angle != 0:
>              new_page.Rotate = angle + angle0
>          # PDF files which do not have mediabox default to Portrait Letter / ANSI A
> ```
with these changes applied to the script it spits out the following:
```python
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/pdfarranger/pdfarranger.py", line 695, in choose_export_pdf_name
    self.save(mode, file_out)
  File "/usr/lib/python3.9/site-packages/pdfarranger/pdfarranger.py", line 157, in wrapper
    func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pdfarranger/pdfarranger.py", line 769, in save
    exporter.export(self.pdfqueue, to_export, file_out, mode, m)
  File "/usr/lib/python3.9/site-packages/pdfarranger/exporter.py", line 162, in export
    print("new_page copy", type(new_page), new_page)
NotImplementedError: don't know how to __str__ this object
```

**Comment by jeromerobert** [comment]
> NotImplementedError: don't know how to __str__ this object

@sillysimon Sorry my patch was wrong. But it does not matter anymore.

> I used a pip3 trick to install the latest pikepdf and other libraries. 

@Just-Another-Gnumer Good clue, thanks.

Arch always have the very latest version pikepdf too.

A workaround is `pip install --user pikepdf==2.5.2`. I'll try to find what to do to fix pdfarranger with pikepdf 2.6.0.

**Comment by Just-Another-Gnumer** [comment]
I took your advice and the saving problem has been resolved. However, I have not managed to solve my other problem. 

 Thank you

**Comment by jeromerobert** [comment]
pikepdf < 2.7.0 does not support libqpdf >= 1.2.0 well enough. The pipy wheel of pikepdf 2.7.5 contains libqpdf 1.1.x so it's working. The pipy wheel of pikepdf 2.6.0 contains libqpdf 1.2.0 so it's not working.

Now that pikepdf 2.7.0 is released (and available in pipy and Arch Linux) I close this issue.

**Comment by dreua** [comment]
Mentioned in the [release notes of pikepdf 2.7.0](https://github.com/pikepdf/pikepdf/blob/master/docs/release_notes.rst#v270) quickly fixed as always :100:

**Comment by vivi90** [comment]
Okay, issue still exists for me.
- OS: Manjaro (Arch) Linux
- Kernel: 5.11
- PDF Arranger: 1.7.0

**Comment by dreua** [comment]
@vivi90 We need your pikepdf and qpdf versions, kernel is irrelevant.

**Comment by m-holger** [comment]
Hi

I had the same issue. I checked the open issues, but did not spot the "pinned issue" - something that I had not noticed before on github

For those of us who only look only at the "open" list, would it be useful to have an open issue (until a new version with the right version dependency is released)   that suggests to users to upgrade their pikepdf with 

pip  install  --user pikepdf==2.8.0

Might save some time.

Thanks

**Comment by vivi90** [comment]
> pip install --user pikepdf==2.8.0

Not working for me:
```bash
$ pip install --user pikepdf==2.8.0
bash: pip: Kommando nicht gefunden.
$ pip3 install --user pikepdf==2.8.0
bash: pip3: Kommando nicht gefunden.
```
_(german for `command not found`)_

Here some further info:
```bash
$ python -V
Python 3.9.1
$ python3 -V
Python 3.9.1
$ pacman -Q python-pikepdf
python-pikepdf 2.5.2-1
```

**Comment by dreua** [comment]
@vivi90 @m-holger The source of this issue is that you have incompatible versions of qpdf and pikepdf. I assume you installed both packages from your distribution's repository, would that be correct? In that case the upgrade to qpdf >= 10.2.0 triggered this issue, please report that to your respective qpdf package maintainers. As a solution you can always downgrade qpdf to 10.1.0 or earlier.

I'm out of time now, but a new issue with workaround information seems like a good idea, feel free to create it, I may edit it when I find the time.

**Comment by vivi90** [comment]
> I assume you installed both packages from your distribution's repository [..]
I just installed `pdfarranger` from the official community repositories of my distribution (Manjaro) after a fresh OS install and some updates.

**Comment by m-holger** [comment]
I installed pdfarranger from source on a Mint 20.1 system using the instructions in README.md for Debian based distributions. I am pretty (99.99%+) sure that pikepdf (2.6.0) was installed as part of the pdfarranger install, and so not a issue with the Mint distribution. As mentioned earlier, upgrading to 2.8.0 worked for me.
(For info, the "flatpak" on Mint works fine)

**Comment by vivi90** [comment]
@m-holger Yes, maybe this line needs to be fixed:
https://github.com/pdfarranger/pdfarranger/blob/0921e5e95111e1b043782e7cfc4b527ff1ef2aa8/setup.py#L54

**Comment by m-holger** [comment]
That was what I was thinking, although I do not know whether there are any negative implications in upgrading for existing users of pikepdf. If there is value in supporting earlier versions of pikepdf, checking that pikepdf.__version__ is not '2.6.0'  would be the alternative. In any case, given that new installs pull the latest version of pikepdf this is unlikely to be an issue going forward.

I have opened a new issue describing the issue/solution. Given that 2.6.0 was available for only 3 days, hopefully not too many users are impacted.

**Comment by jeromerobert** [comment]
Reopenning for people only reading openned bugs.

**Comment by dreua** [comment]
If want to clarify a few things:
- We know that the flatpak works, it's been stated <strike>three</strike>four times now. (Flatpaks are designed to prevent exactly those versioning issues so it is not really big news. They also introduce other issues but that is off topic here.)
- We have two different scenarios which can trigger this issue:
  1. Install with pip in the short timeframe where pikepdf 2.6.0 was the latest pikepdf. This has qpdf bundled and should simply be upgraded as pikepdf 2.6.0 is a bad version.
  2. Installations which use pikepdf and qpdf from other sources, usually the distribution's package repository. In this case the qpdf library is not bundled into pikepdf and the issue can occure with any pikepdf<2.7.0 given that qpdf has been updated more recently than pikepdf (i.e. pikepdf < 2.7.0 or qpdf >= 10.2.0). Fixing this is more difficult, I'd try downgrading or not upgrading qpdf first. (I'm working on a better solution on this, stay tuned.)
- Therefore changing the `install_requires` would only help in very rare cases and it would not help in many others. It's not worth it imo.
- I thought that creating a new issue with specific work around instructions was a good idea but @jeromerobert seems to disagree. That's fine, let's keep all information at one place here.

**Comment by dreua** [comment]
@jeromerobert is there a typo in the libqpdf version that has spread from your first mention of it to different places or is it actually libqpdf 1.2.0 and [qpdf 10.2.0](http://qpdf.sourceforge.net/files/qpdf-manual.html#ref.release-notes)?

**Comment by jeromerobert** [comment]
> I thought that creating a new issue with specific work around instructions was a good idea but @jeromerobert seems to disagree. That's fine, let's keep all information at one place here.

Indeed I think we'll mostly get noise or duplicate information with one issue by case (distro/version/pip/not pip).

As you said, in most case the answer is `pip install --upgrade pikepdf`. In other cases it must be fixed by distro packagers and for them what to do should be obvious.

**Comment by dreua** [comment]
> In other cases it must be fixed by distro packagers and for them what to do should be obvious.

Actually I'm not so sure about the proper distro-fix, I just explained the problem and requested clarification here: https://github.com/pikepdf/pikepdf/issues/174

**Comment by m-holger** [comment]
First of all, I like to thank the team for putting in the time in to create and develop pdfarranger.

If I may, I would like to give my perspective as a simple user of your program to the question of whether to  keep everything related to this issue in one place as preferred by @jeromerobert vs  @dreua 's comment.

I can see that @jeromerobert 's point makes perfect sense from a developer perspective. However, for me as an user much of what is contained in issue 427 is noise. All I need to know is

- its a known and well understood issue (so I know I don't need to report it)
- you cannot directly do anything about it (or you are working on a fix, so I know what to expect)
- what are the recommended work-arounds (so I can fix my problem)

As a user, I hope to find this information easily and in a single place. Having this in an separate issue is one solution (by all means, make it explicit that the issue is for information only and all comments will be deleted), having a known issues section in the README file would be another. Having the work-around intermingled with developer discussions is confusing, especially for users with limited experience.

Apologies for any offence caused, and please feel free to delete as off-topic.

**Comment by vivi90** [comment]
> First of all, I like to thank the team for putting in the time in to create and develop pdfarranger.

Yes, it's a great tool and i am using it for a long time.
Also used it, when it was still called `pdfshuffler`.

> .. having a known issues section in the README file would be another. 

I think this might be the best solution, because it's very easy to find.

> Having the work-around intermingled with developer discussions is confusing, especially for users with limited experience.

Yes, i see it the same way.

**Comment by jeromerobert** [comment]
I plan to release 1.7.1 today or tomorrow.

**Comment by milegrin** [comment]
Thank you greatly.
